import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {

  const months=["January","February","March","April","May","June","July","August","September","October","November","December"]
  const date = new Date();
  const month = months[date.getMonth()];
  const day = date.getDay();
  const year = date.getFullYear();
  return (
    <>
      <Head>
        <title>Digiency - Home page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.png" />
      </Head>

      <header className='bg-[#FFF7F4] md:h-[600px] relative p-4 '>

        <div className="flex justify-around items-center p-4 flex-col md:flex-row">
          <div className="md:ml-[100px] md:w-[400px]">
            <h1 className="font-bold text-4xl leading-[40px]">We Are The Best<br/> <span className='text-[#FF5300]'>Digital Agency</span> For Business</h1>
            <p className="text-sm mt-[40px]">Start by creating a new Next.js project if you don’t have one set up already. The most common approach is to use Create Next App.
            Start by creating a new Next.js project if you don’t have one set up already. The most common approach is to use Create Next App.
            </p>
            <div><button className="bg-[#FF5300] p-2 text-white shadow mt-[30px] w-[150px]">Contact Us</button></div>
          </div>
          <div> <img src="/Frame 19.png" className=""/></div>
        </div>

        <div className='absolute md:-right-[30px] top-[180px] -right-[70px]'>
          <img src="/Socila Icon.png" className="rotate-90 w-[180px]"/>
        </div>

      </header>

      <div className='md:h-[600px] flex items-center justify-center'>
        <div className="flex flex-col-reverse md:flex-row">
          <div>
          <img src="/Image (1).png" className="w-[520px]"/>
          </div>
          <div className="md:ml-[50px] md:w-[500px] px-2">
            <h1 className="font-bold text-3xl leading-[40px]">We Are  <span className='text-[#FF5300]'>Making<br/> Ideas Better</span> For Everyone</h1>
            <p className="text-sm mt-[40px]">Start by creating a new Next.js project if you don’t have one set up already. The most common approach is to use Create Next App.
            Start by creating a new Next.js project if you don’t have one set up already. The most common approach is to use Create Next App.
            </p>
            <p className="text-sm mt-[40px]">Start by creating a new Next.js project if you don’t have one set up already. The most common approach is to use Create Next App.
            Start by creating a new Next.js project 
            </p>
            <div><button className="bg-[#FF5300] p-2 text-white shadow mt-[30px] w-[150px]">Contact Us</button></div>
          </div>
        </div>
      </div>


<div className="flex items-center justify-center md:-mt-[70px]">
  <div className="grid grid-cols-1 md:grid-cols-4 gap-[25px]">

  <div className="flex flex-col items-center justify-center w-[200px] border border-2-gray px-2">
    <img src="/Icon.png"/>
    <p className="text-center text-sm">World leader in consulting and finance</p>
    </div>

    <div className="flex flex-col items-center justify-center w-[200px] border border-2-gray px-2">
    <img src="/Icon (2).png"/>
    <p className="text-center text-sm">World leader in consulting and finance</p>
    </div>

    <div className="flex flex-col items-center justify-center w-[200px] border border-2-gray px-2">
    <img src="/Icon (3).png"/>
    <p className="text-center text-sm">World leader in consulting and finance</p>
    </div>

    <div className="flex flex-col items-center justify-center w-[200px] border border-2-gray p-2">
    <img src="/Icon (1).png"/>
    <p className="text-center text-sm">World leader in consulting and finance</p>
    </div>

    </div>

</div>


<div className='bg-[#FFF7F4] md:h-[650px] relative p-4 mt-[60px] flex items-center justify-center '>
  <div>
    <h2 className='text-left mb-[20px]'>Our Experience</h2>

    <div className='flex justify-around gap-[30px] flex-col md:flex-row'>
      <div className="md:w-[500px]">
        <h1 className="text-4xl">We Have Completed <span className='text-[#FF5300]'>50+ Projects </span>Successfully</h1>

        <p className="text-sm mt-[40px]">Start by creating a new Next.js project if you don’t have one set up already. The most common approach is to use Create Next App.
            Start by creating a new Next.js project if you don’t have one set up already. The most common approach is to use Create Next App.
            </p>
            <p className="text-sm mt-[40px]">Start by creating a new Next.js project if you don’t have one set up already. The most common approach is to use Create Next App.
            Start  
            </p>
            <div><button className="bg-[#FF5300] p-2 text-white shadow mt-[30px] w-[120px] text-sm">Contact Us</button></div>
      </div>
      <div className='grid grid-cols-2 gap-[20px]'>

        <div className="bg-white shadow w-[200px] h-[200px] flex flex-col items-center justify-center ">
          <h3 className='font-bold text-4xl mb-[15px]'>100+</h3>
          <p className='font-bold text-sm'>Global Customers</p>
        </div>
        <div className="bg-white shadow w-[200px] h-[200px] mt-[40px] flex flex-col items-center justify-center">
        <h3 className='font-bold text-4xl mb-[15px]'>50+</h3>
          <p className='font-bold text-sm'>Projects Completed</p>
        </div>
        <div className="bg-white shadow w-[200px] h-[200px] flex flex-col items-center justify-center">
        <h3 className='font-bold text-4xl mb-[15px]'>20+</h3>
          <p className='font-bold text-sm'>Team Members</p>
        </div>
        <div className="bg-white shadow w-[200px] h-[200px] mt-[40px] flex flex-col items-center justify-center">
        <h3 className='font-bold text-4xl mb-[15px]'>2+</h3>
          <p className='font-bold text-sm'>Our Company</p>
        </div>
      </div>
    </div>
  </div>
</div>

<div className='md:h-[700px] Services mt-[60px] flex flex-col items-center justify-center'>
  <div><h2 className='text-center text-[#FF5300] '>Our Services</h2>
  <h1 className='text-center font-bold text-2xl mt-[10px] '>What We DO</h1></div>

  <div className='grid grid-cols-1 md:grid-cols-3 gap-[30px] mt-[50px]'>
    <div className='relative shadow w-[250px] h-[250px] rounded p-2'>
      <img src="/gaming.png"/>
      <div><h2 className="font-bold mb-[5px] mt-[15px]">UX Design</h2>
      <p className="text-sm text-[#EFEFEF] mb-[15px]">Mobile App,Website</p>
      <p className="text-sm">Start by creating a new Next.js project if you don’t have one set

      </p>
      </div>
      <h1 className='text-[#EFEFEF] text-5xl absolute top-[20px] right-[15px]'>01</h1>
    </div>

    <div className='relative shadow w-[250px] h-[250px] rounded p-2'>
      <img src="/digital-marketing.png"/>
      <div><h2 className="font-bold mb-[5px] mt-[15px]">Digital Marketing</h2>
      <p className="text-sm text-[#EFEFEF] mb-[15px]">Mobile App,Website</p>
      <p className="text-sm">Start by creating a new Next.js project if you don’t have one set

      </p>
      </div>
      <h1 className='text-[#EFEFEF] text-5xl absolute top-[20px] right-[15px]'>02</h1>
    </div>


    <div className='relative shadow w-[250px] h-[250px] rounded p-2'>
      <img src="/gaming.png"/>
      <div><h2 className="font-bold mb-[5px] mt-[15px]">UX Design</h2>
      <p className="text-sm text-[#EFEFEF] mb-[15px]">Mobile App,Website</p>
      <p className="text-sm">Start by creating a new Next.js project if you don’t have one set

      </p>
      </div>
      <h1 className='text-[#EFEFEF] text-5xl absolute top-[20px] right-[15px]'>03</h1>
    </div>



    <div className='relative shadow w-[250px] h-[250px] rounded p-2'>
      <img src="/mobile-development.png"/>
      <div><h2 className="font-bold mb-[5px] mt-[15px]">Mobile Development</h2>
      <p className="text-sm text-[#EFEFEF] mb-[15px]">Mobile App,Website</p>
      <p className="text-sm">Start by creating a new Next.js project if you don’t have one set

      </p>
      </div>
      <h1 className='text-[#EFEFEF] text-5xl absolute top-[20px] right-[15px]'>04</h1>
    </div>



    <div className='relative shadow w-[250px] h-[250px] rounded p-2'>
      <img src="/web-design.png"/>
      <div><h2 className="font-bold mb-[5px] mt-[15px]">Web Design</h2>
      <p className="text-sm text-[#EFEFEF] mb-[15px]">Mobile App,Website</p>
      <p className="text-sm">Start by creating a new Next.js project if you don’t have one set

      </p>
      </div>
      <h1 className='text-[#EFEFEF] text-5xl absolute top-[20px] right-[15px]'>05</h1>
    </div>




    <div className='relative shadow w-[250px] h-[250px] rounded p-2'>
      <img src="/gaming.png"/>
      <div><h2 className="font-bold mb-[5px] mt-[15px]">UX Design</h2>
      <p className="text-sm text-[#EFEFEF] mb-[15px]">Mobile App,Website</p>
      <p className="text-sm">Start by creating a new Next.js project if you don’t have one set

      </p>
      </div>
      <h1 className='text-[#EFEFEF] text-5xl absolute top-[20px] right-[15px]'>06</h1>
    </div>
     
  </div>
</div>

<div className='bg-[#FFF7F4] md:h-[550px] relative p-4 mt-[60px] flex items-center justify-center '>

<div className="flex justify-around gap-[60px] flex-col md:flex-row">
          
          <div className="md:ml-[50px] md:w-[500px]">
            <h1 className="font-bold text-3xl leading-[40px]">Grow Your Business With <br/>Our Agency</h1>
            <p className="text-sm mt-[40px]">Start by creating a new Next.js project if you don’t have one set up already. The most common approach is to use Create Next App.
            Start by creating a new Next.js project if you don’t have one set up already. The most common approach is to use Create Next App.
            </p>
            <ul className="text-sm mt-[25px] gap-[10px] flex flex-col">
              <li>Innovative web design</li>
              <li>UI/UX design with global trends</li>
              <li>Web and email hosting services</li>
              <li>Digital marketing</li>
            </ul>
            <div><button className="bg-[#FF5300] p-2 text-white shadow mt-[30px] w-[150px]">Contact Us</button></div>
          </div>
          <div>
          <img src="/Frame 20.png" className="w-[520px]"/>
          </div>
        </div>

</div>


<div className="md:h-[500px] mt-[60px] members flex items-center justify-center p-4 flex-col">
<div>
  <h3 className="text-[#D6D6D6] text-center mb-[25px] text-sm">Team Member</h3>
  <h1 className="text-center text-2xl mb-[30px] font-bold">We Have<br/> <span className="text-[#FF5300]">Some Awesome</span> Members</h1>
</div>
  <div className="grid grid-cols-1 md:grid-cols-4 gap-[20px] p-4">
    <div>
      <img src="./Image (2).png"/>
      <div className="w-[270px] h-[70px] shadow flex flex-col items-center justify-center">
        <h3 className="font-bold mb-[10px]"> Talan Horrif</h3>
        <p className="text-[#D6D6D6] text-center  text-sm">Web developer</p>
      </div>
    </div>
    <div>
    <img src="./Image (3).png"/>
      <div className="w-[270px] h-[70px] shadow flex flex-col items-center justify-center">
      <h3 className="font-bold mb-[10px]"> Talan Horrif</h3>
        <p className="text-[#D6D6D6] text-center  text-sm">Web developer</p>
      </div>
    </div>
    <div>
    <img src="./Image (4).png"/>
      <div className="w-[270px] h-[70px] shadow flex flex-col items-center justify-center">
      <h3 className="font-bold mb-[10px]"> Philips Courtis</h3>
        <p className="text-[#D6D6D6] text-center  text-sm">App developer</p>
      </div>
    </div>
    <div>
    <img src="./Image (3).png"/>
      <div className="w-[270px] h-[70px] shadow flex flex-col items-center justify-center">
      <h3 className="font-bold mb-[10px]"> Gustava Hertaiwz</h3>
        <p className="text-[#D6D6D6] text-center  text-sm">UIUX Designer</p>
      </div>
    </div>
  </div>
</div>

<div className="projects mt-[60px] members flex items-center justify-center p-4 flex-col">

<div>
  <h3 className="text-[#D6D6D6] text-center mb-[25px] text-sm">Our Work</h3>
  <h1 className="text-center text-2xl mb-[30px] font-bold">We Have Some<br/> <span className="text-[#FF5300]">Designed $ Development </span> Projects</h1>
  <ul className="flex gap-[30px] text-sm">
    <li>All</li>
    <li>Graphics design</li>
    <li>Web development</li>
    <li>UiUx design</li>
  </ul>
</div>

<div className="grid grid-cols-1 md:grid-cols-3 mt-[30px]">
  <div>
    <img src="/Image@2x.png" className="w-[350px]"/>
  </div>
  <div>
    <img src="/Image@2x.png" className="w-[350px]"/>
  </div>
  <div>
    <img src="/Image@2x.png" className="w-[350px]"/>
  </div>
  <div>
    <img src="/Image@2x.png" className="w-[350px]"/>
  </div>
  <div>
    <img src="/Image@2x.png" className="w-[350px]"/>
  </div>
  <div>
    <img src="/Image.png" className="w-[350px]"/>
  </div>
</div>

</div>


<div className='bg-white md:h-[550px] relative p-4 mt-[60px] flex items-center justify-center '>

<div className="flex justify-around gap-[60px] flex-col md:flex-row">
          
          <div className="md:ml-[50px] md:w-[500px]">
            <h2 className="text-[#FF5300] font-bold mb-[20px]">Our Capabilities</h2>
            <h1 className="font-bold text-3xl leading-[40px]">Forward Thinking Team Of <br/>Designers & Devlopers</h1>
            <p className="text-sm mt-[40px]">Start by creating a new Next.js project if you don’t have one set up already. The most common approach is to use Create Next App.
            Start by creating a new Next.js project. s project if you don’t have one set up
            </p>
            <div className="mt-[30px] grid grid-cols-2 gap-[15px]  md:grid-cols-4">
              <div className="w-[100px] h-[100px] shadow rounded flex flex-col items-center justify-center px-4">
                  <h3 className="text-[#FF5300] font-bold mb-[10px] text-2xl">85%</h3>
                  <p className="text-center text-sm">Software development</p>
              </div>
              <div className="w-[100px] h-[100px] shadow rounded flex-col items-center justify-center px-4 flex">
              <h3 className="text-[#FF5300] font-bold mb-[10px] text-2xl">90%</h3>
                  <p className="text-center text-sm">Graphics Design</p>
              </div>
              <div className="w-[100px] h-[100px] shadow rounded flex-col items-center justify-center px-4 flex">
              <h3 className="text-[#FF5300] font-bold mb-[10px] text-2xl">75%</h3>
                  <p className="text-center text-sm">Game design</p>
              </div>
              <div className="w-[100px] h-[100px] shadow rounded flex-col items-center justify-center px-4 flex">
              <h3 className="text-[#FF5300] font-bold mb-[10px] text-2xl">100%</h3>
                  <p className="text-center text-sm">Web development</p>
              </div>
            </div>
           
          </div>
          <div>
          <img src="/Frame 21.png" className="w-[520px]"/>
          </div>
        </div>

</div>


<div className='bg-[#FFF7F4] md:h-[450px] relative p-4 mt-[60px] flex items-center justify-center flex-col'>
<div>
  <h3 className="text-[#D6D6D6] text-center mb-[25px] text-sm">Clients Feedback</h3>
  <h1 className="text-center text-2xl mb-[30px] font-bold"> Some <span className="text-[#FF5300]">Great </span><br/><span className="text-[#FF5300]">Words </span>From Our Clients</h1>
 
</div>

<div className="flex gap-[60px] flex-col md:flex-row">
  <div className="bg-[#FF5300] h-[200px] w-[350px] text-white relative px-4 ">
    <div className="flex gap-[40px] items-center">
    <img src="/Image (5).png" className="-ml-[30px] mt-[30px]"/>
    <div><h2 className="font-bold">Josephine John</h2>
    <p className="text-sm">CEO</p></div>
    </div>

    <div className="mt-[17px]"><p className="text-sm text-center">Start by creating a new Next.js project if you don’t have one set up already. new Next.js project. 
     </p></div>
    
  </div>
  <div className="bg-[#FF5300] h-[200px] w-[350px] text-white px-4">
  <div className="flex gap-[40px] items-center">
    <img src="/Profile.png" className="-ml-[30px] mt-[30px]"/>
    <div><h2 className="font-bold">Josephine John</h2>
    <p className="text-sm">CEO</p></div>
    </div>

    <div className="mt-[17px]"><p className="text-sm text-center">Start by creating a new Next.js project if you don’t have one set up already. new Next.js project. 
     </p></div>
  </div>
</div>
</div>

<div className='bg-white  relative p-4 mt-[60px] flex items-center justify-center flex-col'>
<div>
  <h3 className="text-[#D6D6D6] text-center mb-[25px] text-sm">Contact Us</h3>
  <h1 className="text-center text-2xl mb-[30px] font-bold"> Feel <span className="text-[#FF5300]">Free </span><br/><span className="text-[#FF5300]">To Contact </span>With Us</h1>
 
</div>

<div className="grid grid-cols-1 md:grid-cols-3 gap-[20px]">
<div className="bg-white shadow w-[200px] h-[200px] flex flex-col items-center justify-center ">
  <div className="flex items-center ">
    <img src="/mail.png"/>
    <div><h3 className="text-[#FF5300] ">Drop a line</h3>
    <h2 className=" font-bold">Mail Us</h2></div>
  </div>
  <div className="text-sm">infodigiency@gmail.com <br/>hikay123@gmail.com</div>
</div>
<div className="bg-white shadow w-[200px] h-[200px] flex flex-col items-center justify-center ">
  <div className="flex items-center ">
    <img src="/map-pin.png"/>
    <div><h3 className="text-[#FF5300] ">Location</h3>
    <h2 className=" font-bold">Visit Us</h2></div>
  </div>
  <div className="text-sm">infodigiency@gmail.com <br/>hikay123@gmail.com</div>
</div>

<div className="bg-white shadow w-[200px] h-[200px] flex flex-col items-center justify-center ">
  <div className="flex items-center ">
    <img src="/phone-call.png"/>
    <div><h3 className="text-[#FF5300] ">24/7 Services</h3>
    <h2 className=" font-bold">Call Us</h2></div>
  </div>
  <div className="text-sm">09061182935 <br/>08148837221</div>
</div>

</div>
<div className='flex items-center justify-center flex-col md:flex-row'>
  <img src="/Image (6).png"/>

  <div>
  <div className="  flex flex-col items-center p-[30px]" id="contact">

      <div className="py-4">
        <h2 className="font-bold text-2xl text-center m-3">Send <span className="text-[#FF5300]">Your Message To Us</span></h2>
       
      </div>
      <div className="flex flex-col  justify-center">
<div className="flex flex-col md:flex-row gap-[15px] "><input type="email" placeholder='Email' className="md:p-2 w-[350px] p-3 md:w-[200px] shadow"/><input type="email" placeholder='Your Name' className="md:p-2 w-[350px] p-3 md:w-[200px] shadow"/></div><br/>
<div className="flex flex-col md:flex-row gap-[15px] "><input type="email" placeholder='Reason for contacting'className="md:p-2 w-[350px] shadow p-3 md:w-[200px]"/><input type="email" placeholder='Phone' className="md:p-2 w-[350px] p-3 md:w-[200px] shadow"/></div><br/>
<div><textarea   placeholder="Message" className="md:p-2 w-[350px] p-3  h-[150px] md:w-[480px] shadow"/></div>
<div><button className="bg-[#FF5300] text-white p-2 shadow w-[200px] mt-[20px] ">Submit</button></div>
      </div>
    </div>
    
  </div>

  
</div>

</div>
<div className='bg-[#FFF7F4] md:h-[500px] relative p-4 mt-[60px] flex items-center justify-center flex-col'>
<div>
  <h3 className="text-[#D6D6D6] text-center mb-[25px] text-sm">Our Blog</h3>
  <h1 className="text-center text-2xl mb-[30px] font-bold"> Our Latest <span className="text-[#FF5300]">Blogs </span><br/><span className="text-[#FF5300]">Will Keep </span>Everyone Updated</h1>
 
</div>
<div className="grid grid-cols-1 md:grid-cols-3 gap-[10px] p-4">
  <div className="relative shadow md:w-[400px] p-4 bg-white">
    <img src="/Image (7).png" className="absolute top-[10px] right-[10px] w-[100px]"/>
    <div>
      <h2 className="text-sm mb-[20px] text-[#FF5300]">Graphics design</h2>
      <h1 className="font-semibold text-1xl w-[250px]">Ridiculously powerful 2021 iPad Pro may drop this month</h1>
      <div className="flex mt-[15px] gap-[15px]">
      <img src="/Profile (1).png" className="w-[50px]"/>
      <div> <h2 className="font-bold text-sm">Christopher John</h2>
      <p className="text-sm text-[#D6D6D6]">{month} {day},{year}. 5 min read</p></div>
      </div>
    </div>

  </div>
  <div className="relative shadow md:w-[400px] p-4 bg-white">
    <img src="/Image (7).png" className="absolute top-[10px] right-[10px] w-[100px]"/>
    <div>
      <h2 className="text-sm mb-[20px] text-[#FF5300]">Graphics design</h2>
      <h1 className="font-semibold text-1xl w-[250px]">35 Stellar Graphic design Blogs to Keep You Educated and Inspired</h1>
      <div className="flex mt-[15px] gap-[15px]">
      <img src="/Profile (1).png" className="w-[50px]"/>
      <div> <h2 className="font-bold text-sm">Christopher John</h2>
      <p className="text-sm text-[#D6D6D6]">{month} {day},{year} . 5 min read</p></div>
      </div>
    </div>

  </div>
  <div className="relative shadow md:w-[400px] p-4 bg-white">
    <img src="/Image (7).png" className="absolute top-[10px] right-[10px] w-[100px]"/>
    <div>
      <h2 className="text-sm mb-[20px] text-[#FF5300]">Graphics design</h2>
      <h1 className="font-semibold text-1xl w-[250px]">35 Stellar Graphic design Blogs to Keep You Educated and Inspired</h1>
      <div className="flex mt-[15px] gap-[15px]">
      <img src="/Profile (1).png" className="w-[50px]"/>
      <div> <h2 className="font-bold text-sm">Christopher John</h2>
      <p className="text-sm text-[#D6D6D6]">{month} {day},{year} . 5 min read</p></div>
     
      </div>
    </div>

  </div>


</div>

</div>

<div className='flex items-center justify-center mt-[70px]'>
  <img src="/Map.png"/>
</div>

<div className="flex items-center justify-center">
  <div className="mt-[60px] grid grid-cols-4 gap-[50px] p-[40px]">
  <img src="/Frame 1.png"/>
  <img src="/Frame 2.png"/>
  <img src="/Frame 3.png"/>
  <img src="/Frame 4.png"/>
  </div>
</div>
     
    </>
  )
}
